# Generated by Django 3.2.3 on 2021-05-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('publish_time', models.DateTimeField()),
            ],
        ),
    ]
