# Generated by Django 3.2.3 on 2021-05-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YoutubeData',
        ),
    ]
